name: flutter_froghome_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flex_color_scheme: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  multi_select_flutter: ^4.1.2
  flutter_tags_x: ^1.1.0
  jiffy: ^5.0.0
  flutter_slidable: ^2.0.0
  clipboard: ^0.1.3
  excel: 
    git: https://github.com/justkawal/excel
  share_plus: ^4.5.3
  cross_file: ^0.3.3+2
  open_filex: ^4.1.1
  fluttertoast: ^8.0.9

dev_dependencies: 
  flutter_lints: 2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli:
  sub_folder: false