name: flutter_froghome_app
version: 0.0.1+3
publish_to: 
description: 台灣兩棲蛙類調查工具
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flex_color_scheme: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11  
  jiffy: ^5.0.0
  flutter_slidable: ^2.0.0
  clipboard: ^0.1.3
  excel: 
    git: https://github.com/justkawal/excel
  share_plus: ^6.0.0
  cross_file: ^0.3.3+2
  flutter_launcher_icons:
    git: 
      url: https://github.com/fluttercommunity/flutter_launcher_icons
      ref: master
  url_launcher: ^6.1.6
  jsaver: ^1.0.0
  package_info_plus: ^3.0.0
  firebase_core: ^2.0.0
  firebase_analytics: ^10.0.2


dev_dependencies: 
  flutter_lints: 2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.2.0  
  flutter_test: 
    sdk: flutter

flutter_icons:
  image_path: "assets/logo/logo_v2.png"
  min_sdk_android: 21
  android:
    generate: true    
    #adaptive_icon_foreground: "assets/logo/ic_launcher_foreground.png"
    #adaptive_icon_background: "assets/logo/background-c4e997.png"
    #adaptive_icon_background: "#ff0000ff"
    # adaptive_icon_background: "#EB6F93"
  linux: 
    generate: true
    image_path: "assets/logo/logo_v2.png"
  windows:
    generate: true
    image_path: "assets/logo/logo_v2.png"

  web:
    generate: true
    image_path: "assets/logo/logo_v2.png"
  

flutter: 
  uses-material-design: true
  assets:
    - assets/images/logo.png

get_cli:
  sub_folder: false

