name: flutter_froghome_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^5.0.0-beta.52
  flutter: 
    sdk: flutter
  flex_color_scheme: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_awesome_select: ^6.5.0

dev_dependencies: 
  flutter_lints: 2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

get_cli:
  sub_folder: false